"""empty message

Revision ID: 015bee148e79
Revises: 562032fb1961
Create Date: 2024-02-06 19:22:47.138776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '015bee148e79'
down_revision = '562032fb1961'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
